### PR TITLE
Add combobox/dropdown

### PR DESCRIPTION
**Pull request by almarklein**
* A `ComboBox` is an optionally editable dropdown button
* A `DropdownContainer` can hide a widget out of sight.

### CODE REVIEW

**Comment by Korijn** [comment]
@ivoflipse

**Comment by Korijn** [comment]
Can you provide different values for the option tag value and text attributes?

**Comment by almarklein** [comment]
I am not sure what you mean. You can always set the `text` property programatically (to something that does not match an option).

The options are just strings, and these are the strings that are used to set `text`. If you want some sort of mapping, its probably easiest to use `selected_index`.

And not that I think of it, that should probably be renamed to `current_index`.

**Comment by ivoflipse** [comment]
I think Korijn was referring to a select tag, where there's a difference between the value of an option and the text it displays in the dropdown

```
<select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
```

At the moment, the flexx widget doesn't support this behavior, since it's not a select tag, but a custom dropdown. We'd have to maintain our own mapping of human readable values to values our program would want to use

**Comment by almarklein** [comment]
If it's a common use-case, we can think about supporting something like this. E.g. by allowing to specify tuples.

**Comment by almarklein** [comment]
Though the `value` in `<option>` is sorta like the `index` in our implementation, except its a key instead of an int.

**Comment by Korijn** [comment]
Our use case is a dictionary mapping abbreviations to full names going into the combobox as <option value="abbr">full</option>

**Comment by almarklein** [comment]
What about adding `selected_key`,which contains the "key" corresponding to a selected item (`None` if no item is selected or if the selected item has no key). The `options` prop can then be a list of key-value pairs, or a just a dictionary.

A variant of this: rename `selected_index` to `selected_key`, or maybe just `selected`. This prop contains the key for the selected item, or its index if the selected item has no key.

**Comment by Korijn** [comment]
`selected_index` together with dict or keyval pairs as `options` would be sufficient, I think.

**Comment by almarklein** [comment]
Mmm ... that would mean you would lookup the key using `combobox.options[combobox.selected_index][0]`. Which seems rather non-trivial.

**Comment by Korijn** [comment]
Right. So the selected key addition would make it easier.

**Comment by Korijn** [comment]
Here's our use case:

image

We'd like to display human readable text, but still get the (currently displayed) value from a `selected_value` property.

So a dict would be much better.

**Comment by almarklein** [comment]
See #250

**Pull request merged**
