### PR TITLE
Model.init() can now have args

### LINKED ISSUE #228: Provide models with initial data
Sometimes a model needs information at initialization time, that you want to provide in a flexible way, something like:

```py
class MyModel(app.Model):

    def init(self, the_info):
         ...

...

m = MyModel(the_info=...)
```

Currently, the `init()` is always argumentless. The required behavior can be achieved by making a property `info`, the value of which can be used inside the `init()`. However, a property suggests that the info can be modified/reset after the model is instantiated, which is not always the case.

In other words, there are situations where a `Model` needs information at initialization time, but for which a property does not make sense conceptually.

Some possible solutions:

A. Any keyword arguments used to instantiate a `Model` which do not correspond to properties are passed to the `init()` as kwargs. You'd thus need to write it like `def init(self, info=None)` to make it a keyword arg. In theory it could also map to positional args by inspecting the signature, but that feels a bit too magical, I think. 

I am a bit worried about error reporting if a user makes a type in a property name. We would need to inspect the `init()` sig to see what kwargs it accepts, so we can be sure that a kwarg is intended for the `init()`. This should thus be disallowed: `def init(self, **kwargs)`.

B. Provide a new kind of property, similar to the current `readonly` that *must* be provided at initialization and is readonly afterwards. This adds less conceptual stuff for the user to learn, as it's just a kind of property.

C. Use positional arguments. The `Model.__init__()` could catch the positional arguments and pass them to the `init()`. The only downside is that for Models run as an app via `app.launch` or `app.serve` we'd need to provide a way to set these args, but we already do that for the kwargs, so I guess that could work ...

cc @korijn @Maxyme

### PR DESCRIPTION
**Pull request by almarklein**
Fixes #228. Relates to closed issue #140 and PR #199.

So you can do:
```py

class MyModel(app.Model):
    def init(foo, bar=3):
        ...

...
m = MyModel(7, 8, **properties_are_passed_as_kwargs_as_usual)
```

### CODE REVIEW

**Comment by almarklein** [comment]
One thing that I'd like to solve is how to make this work with `app.launch` and `app.serve`. API, wise, I think this would be really nice (and better than the current properties arg):
```py
app.launch(SomeModel.pre_init(3, 4, text='bla'), 'firefox')
```

Implementation wise, this needs some thought. Making `pre_init` return an actual `Model` class would make it Just Work, but would probably involve meta class stuff like `__new__`. It would have to be a class with the same name, but that's ... weird, and also all Model classes get registered to make them available in JS, which complicates things.

Easier is to wrap the class + args + kwargs in a simple object, and then make `app.launch` and friends aware of that.

**Comment by Korijn** [comment]
With regards to `app.launch` and `app.serve`, I would think you can already pass initial data along as per https://github.com/zoofIO/flexx/issues/140?

**Comment by almarklein** [comment]
That was only for keyword arguments. We could extend that approach for positional arguments, in which case it would look like:
```py
app.launch(SomeModel, 'firefox', init_args=[3, 4], properties={'text': 'bla'})
```
This should work, but I don't like it a lot, since I'd rather define the args and kwargs using an actual *call* to something. Or at least explore that idea :)

Let's try:
```py
# A: Extending current approach
app.launch(SomeModel, 'firefox', init_args=[3, 4], properties={'text': 'bla'})

# B: Using a factory func. Possibly useful in other ways. But rather verbose.
app.launch(SomeModel, 'firefox', factory=lambda: SomeModel(3, 4, text='bla'))

# C: Collecting args separately. Feels weird?
app.launch(SomeModel, 'firefox', model_args=app.get_args(3, 4, text='bla'))

# D: Collecting args and class together. I like the compactness.
app.launch(SomeModel.pre_init(3, 4, text='bla'), 'firefox')

# E: Like D, but more explicit.
app.launch(app.pre_init(SomeModel, 3, 4, text='bla'), 'firefox')
```

In `D` and `E`, the first object in `app.launch` is a "factory object" that exposes the class that it will create an instance of. Potentially, such objects can generate instances in other ways, bringing the same flexibility as `B`.

Thoughs, ideas?

**Comment by Korijn** [comment]
What devs will try intuitively is:

```python
app.launch(SomeModel(3, 4, text='bla'), 'firefox')
```

:)

**Comment by almarklein** [comment]
Cannot work; it needs a session. Also `app.serve(SomeModel(3, 4, text='bla'), 'firefox')` cannot work.

**Comment by Korijn** [comment]
A seems easiest to me; kinda reminds of threading.Thread which should be familiar to most pythonistas!

**Comment by almarklein** [comment]
> I would call 'em just args and kwargs though.

Mmm, maybe they should just be the `*args` and `**kwargs`. The thing holding me back with this is the fact that `app.export` and `app.launch` need to be able to receive additional info. But maybe this can be done by popping a name off the kwargs:

```py
# F: use args and kwargs of launch/serve
app.launch(SomeModel, 'firefox', 3, 4, text='bla')
# and export and launch would have 
app.launch(SomeModel, 'firefox', 3, 4, text='bla', runtime_options=dict(title='bla', size=(100, 100)))
app.export(SomeModel, 'firefox', 3, 4, text='bla', export_options=dict(inline=True))
```

**Comment by almarklein** [comment]
(last attempt, otherwise we just go with A)

**Comment by Korijn** [comment]
Here's an out of the box suggestion:

```python
app = App(SomeModel, 3, 4, text='bla')
app.launch('firefox', dict(title='bla', size=(100, 100)))
app.export(dict(inline=True))
```
Ultimately it's your decision, I can live with any option, but I think simplicity is key in getting devs to pick up on it.

**Comment by Korijn** [comment]
Or perhaps:

```python
my_app = app.create(SomeModel, 3, 4, text='bla')
my_app.launch('firefox', dict(title='bla', size=(100, 100)
my_app.export(dict(inline=True))
```

Although, I find the `App(...)` constructor more intuitive since you are actually constructing an app. The global `app.create(...)` is less obvious; using an invisible global app to create sub apps. It's more like a server then, e.g. `server.create_app(...)`

**Comment by almarklein** [comment]
I think I like that! Technically, its very similar to what I proposed with D and E, but by calling it an app and giving it some extra methods it makes a lot more sense.

So these would be equivalent:
```py
app.App(SomeModel, 3, 4, text='bla').launch('firefox', ...)
app.launch(app.App(SomeModel, 3, 4, text='bla'), 'firefox', ...)
```

**Comment by almarklein** [comment]
Ok. I', merging the first bit, and will do the thing with the `App` class in #238, because I foresee some merge conflicts if I do it now.

**Pull request merged**
