### PR TITLE
Settle on a syntax for connection strings

### LINKED ISSUE #194: Connection string micro language
The connection string is already a powerful mechanism to connect to events. With dynamism, selection of all elements in a list, and in #172 deep selectors. Let's think of what we want the language to look like. How far do we want to take it. Are there any other useful features we could add?

I think the language should be simple and easy to remember. I don't think making it look like regexp is a good idea. Rather make it look more like Python. 
- We have paths / dynamism: `parent.title`, `foo.bar.spam.eggs`
- We have selecting all: was `children.*.value` -> new syntax per #172 is `children*.value`, could possibly also be `children[:].value`?
- In that line of thought we couls also allow `children[0].value` and `children[:-2].value`. I can hardly imagine a use-case though.
- Deep selectors: `children**.value`
- Optional selectors? `children.children?.value` looks either one or two levels deep.
- Force connection: if per #188 we will raise an error when connecting to an unknown event, `foo!` can be used to connect anyway.

cc @korijn @ivoflipse

### PR DESCRIPTION
**Pull request by almarklein**
* Fixes #194: formalize the syntax for connection strings.
* Make sure normalization/checks are done in the right places.
* Fixes connection string that end in deep connector.
* Fixes a few other corner cases that where bugs but simply never showed up yet.
* The code grew somewhat, so I had to finally make `evaljs` pass the code to `node` via a file.
* Which gave some space, so I got rid of the `Ƥ` placeholder for `prototype`.
* Make functions not anonymous (which makes handlers for which no label is specified sill still have a sensible label).

### CODE REVIEW

**Comment by almarklein** [comment]
I'll wait with merging till Monday, just in case.

**Comment by Korijn** [comment]
I think we had a case where the combination of ! and ** generated a failure, or at least an unintuitive error message.

**Comment by almarklein** [comment]
That should be fixed by this PR (though now it should be written as `foo.children**!`; the old syntax (w.r.t. the position of the `!` will still work, but you'll get a warning.

**Comment by almarklein** [comment]
... actually, now that I have slept over it, I think I'd like the `!` to be at the very start of the string, so `!foo.children**`. Som context: I initially thought that the ! could be applied to any part of the path, but this is not true; it only makes sense for the final step, so a connection string should be "forced" as a whole. Yesterday I thought the end would be the best place, but the reason was based on an implementation detail, the start is better, I now think, from the user's perspective.

**Pull request merged**
