### PR TITLE
add config tornado_debug to allow running tornado in debug mode

### PR DESCRIPTION
**Pull request by gregfreeman**
Here's a pull request for  issue #393 that I just created.   

I added a config attribute to set tornado debug mode.   

I tried some test scripts for this, but it was a little tricky reloading the app without reloading the test.

### CODE REVIEW

**Comment by almarklein** [comment]
This sounds like it can be useful. Since all this does is pass an argument to Tornado, and is a feature only used by specific users (devs), let's assume that Tornado tested this feature and "manually test" whether it works with Flexx.

**Comment by almarklein** [comment]
Travis seems to be a bit glitchy lately, but it turned green after rerunning.

**Comment by almarklein** [comment]
Is this ready from your end?

**Comment by gregfreeman** [comment]
Yes

On Aug 23, 2017 05:33, "Almar Klein" <notifications@github.com> wrote:

Is this ready from your end?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zoofIO/flexx/pull/394#issuecomment-324289675>, or mute
the thread

**Comment by almarklein** [comment]
Thanks!

**Pull request merged**
