### PR TITLE
Prevent default action for key press if widget has listeners

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Comment by Korijn** [comment]
How does this work? Tabindex is used to change the order in which you tab through all the UI elements, no?

**Comment by almarklein** [comment]
Yes. But in this case it is only used as a marker; when `tabindex` is not `None` the widget is receptive to having focus and able to receive key events. There is code in this same module that sets `tabindex` to `-1` if a connection to a key event is made.

**Comment by Korijn** [comment]
OK. Seems a bit brittle to me but I'm sure it'll work.

**Comment by almarklein** [comment]
The worst that can happen is that the user sets the `tabindex` while there are no connections to key events. In that case the widget will prevent default actions even though it might not be necessary. A user setting `tabindex` to `None` would prevent receiving key events altogether.

**Comment by Korijn** [comment]
The other worry I have is that the future us might not remember this a year from now, and break it when refactoring `tabindex` functionality. :)

**Comment by almarklein** [comment]
Right. I get your point. But the `tabindex` code is in the same module and there is a clear comment why we use it, so I' relatively confident that this will work out ok. I owe you a beer if it does not :P

**Comment by Korijn** [comment]
Deal.

**Comment by almarklein** [comment]
Mmm, I just found that I cannot use F12 to open the developer console in a certain situation. Very annoying. Maybe we should tune this back a bit somehow...

**Comment by almarklein** [comment]
Proposal:

A class attribute `CAPTURE_KEYS` that can be set to `True` to capture all, or to a function that can return True to capture only certain key combo's.

**Comment by almarklein** [comment]
Another possibility, perhaps: 

The default actions occur on press. So we could allow the default event handlers for `key_down` to somehow set a flag to prevent the default action.

**Comment by Korijn** [comment]
The hook where you can call preventDefault yourself seems most flexible to me.

**Comment by almarklein** [comment]
#257

**Comment by almarklein** [comment]
@Korijn thanks. You're right I was about to over-design it.

**Pull request merged**
